apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  sources:
    # ArgoCD polls git repo every 3 minutes
    # repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    - repoURL: https://github.com/HaeyoonJo/argocd-config.git
      targetRevision: HEAD
      path: dev
    - repoURL: https://github.com/HaeyoonJo/argocd-config.git
      targetRevison: HEAD
      path: nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      # by default, automatic sync won't delete resources, so we set here to be "true"
      # which ArgoCD will delete resources when it's needed
      prune: true